[mgr]
show_hidden = true

[opener]
edit = [
  { run = 'helix "$@"', block = true },
]
# open = [
#   { run = 'glow "$@"', block = true, desc = "Glow" },
# ]
open = [
  { run = "xdg-open %s", desc = "Open" },
]

[open]
prepend_rules = [
  { name = "*.md", use = ["open", "edit"] },
]
